name: zenity
description: Desktop UI library to show simple dialog boxes and forms. Uses Zenity under-the-hood.
version: 1.0.1
homepage: https://github.com/tejainece/zenity.dart
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  meta: ^1.1.2

dev_dependencies:
  test: ^0.12.0
